#!/usr/bin/bash

ENV=$1

if [[ "$ENV" == "" ]]; then
  echo fatal: no environment was specified, how am i supposed to run\
    this app?
  echo help: try \`./run prod\' or \`./run dev\'
  exit 1
fi

# running variables
export FLASK_APP=imageserver.imageserver

if [[ "$ENV" == "dev" ]]; then
  export FLASK_DEBUG=1
  flask run
elif [[ "$ENV" == "prod" ]]; then
  PORT=$2
  if [[ "$PORT" == "" ]]; then
    echo warn: no port specified, using 5000
    echo help: try \`./run prod PORT_HERE\'
    PORT=5000
  fi
  flask run --host "0.0.0.0" --port $PORT
else
  echo fatal: unknown environment
  echo help: try \`./run prod\' or \`./run dev\'
  exit 1
fi
